### ISSUE TITLE
Update this guide to FT 3.0

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/iguide-retry-timeout#143]

**Comment by dmorgant** [comment]
Maven is currently showing the last release of openliberty as Nov 20, 2020.  

![image](https://user-images.githubusercontent.com/29490139/105523212-c2a5c300-5ca3-11eb-9071-35fb8772eaa4.png)

Waiting for maven to be updated to update guides to MP FT 3.0.

NOTE: no new content for the guide according to http://eclipse.c3sl.ufpr.br/microprofile/microprofile-fault-tolerance-3.0/microprofile-fault-tolerance-spec-3.0.pdf.
